// lib/mom-template.ts — the ONE professional MinuteX MoM template.
//
// The architecture this file exists to enforce:
//
//     AI structured content -> MoM editor -> user edits -> final data model
//                                 |
//                                 v
//                     THIS FIXED TEMPLATE  ->  DOCX / PDF / preview
//
// Content is the user's. Design is MinuteX's, and is never model-generated.
// So every colour, size, margin and spacing decision the three renderers make
// lives HERE, as data — not duplicated across lib/mom-html.ts (PDF + preview)
// and lib/mom-docx.ts (Word). Those two produce very different output formats
// from the same numbers, which is the only way a PDF and a DOCX of the same
// MoM can actually look alike.
//
// Phase 2 adds multiple templates by making these values a parameter rather
// than a constant. Nothing else has to change: neither renderer hard-codes a
// colour or a size.
//
// Colour is MinuteX blue (theme.tsx's C.primary), NOT the purple of the
// original reference — deliberately, so a generated document is recognisably
// the same product as the app that made it.
import { COMPANY } from "./theme";

export const MOM_TEMPLATE = {
  /** Section headings, table header fill, the rule under the masthead. */
  accent: "3E6BFF",
  accentSoft: "EEF2FF",
  ink: "12131A",
  inkDim: "5B6072",
  inkFaint: "9297A8",
  rule: "E6E9F0",
  zebra: "F7F8FB",

  /** Points. DOCX needs half-points and twips; the converters below do that
   * arithmetic once so neither renderer repeats it. */
  titlePt: 22,
  subtitlePt: 13,
  headingPt: 12,
  bodyPt: 10.5,
  tablePt: 9.5,
  kickerPt: 8,
  footerPt: 8,

  /** Page geometry, in inches. US Letter with a 0.9" margin — wide enough for
   * a six-column table without the cells collapsing, narrow enough that long
   * prose does not run to an uncomfortable measure. */
  pageWidthIn: 8.5,
  pageHeightIn: 11,
  marginIn: 0.9,

  company: COMPANY,
  footerNote:
    "Generated by MinuteX from the meeting recording. Review before circulating.",
} as const;

/** Usable text width, in inches — page width less both margins. */
export const CONTENT_WIDTH_IN =
  MOM_TEMPLATE.pageWidthIn - MOM_TEMPLATE.marginIn * 2;

/** Points -> DOCX half-points (w:sz). */
export const halfPt = (pt: number) => Math.round(pt * 2);

/** Inches -> DOCX twips (1440 per inch): page size, margins, table widths. */
export const twips = (inches: number) => Math.round(inches * 1440);

/** The full content width in twips — every table spans it exactly, so tables
 * in one document all line up with each other and with the body text. */
export const CONTENT_WIDTH_TWIPS = twips(CONTENT_WIDTH_IN);

/**
 * Relative column widths for a table, as fractions summing to 1.
 *
 * Equal columns look wrong on the tables this template actually produces: a
 * "Sr. No" column needs a fraction of the width a "Discussion Point" needs,
 * and giving them the same space both wastes the page and wraps the prose to
 * three lines. So a column is measured by its HEADER, which is the only
 * reliable signal available before the content is known — narrow for an index
 * or a short label, wide for anything prose-like.
 */
export function columnWeights(labels: string[]): number[] {
  if (!labels.length) return [];
  const weight = (label: string) => {
    const l = label.trim().toLowerCase();
    if (/^(sr\.?\s*no\.?|s\.?\s*no\.?|#|no\.?|index)$/.test(l)) return 0.55;
    if (/^(owner|name|by|assignee|responsible|status|priority)$/.test(l)) return 1.3;
    if (/^(date|time|deadline|due|when|target)$/.test(l)) return 1.1;
    if (/(point|discussion|description|detail|note|action|item|topic|remark)/.test(l)) return 2.6;
    // Unknown header: assume prose-ish, since that is the common case for a
    // column a user added by hand.
    return 1.6;
  };
  const raw = labels.map(weight);
  const total = raw.reduce((a, b) => a + b, 0);
  return raw.map((w) => w / total);
}

/** Escape for XML/HTML text nodes. Both renderers escape BEFORE introducing
 * any markup, so document text can never inject tags into the output. */
export function escapeMarkup(s: string): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}

/** The document's date line. One unambiguous format, not a locale guess —
 * the file may be opened by anyone. */
export function templateDate(d: Date = new Date()): string {
  return `${d.getDate()} ${d.toLocaleString("en-GB", { month: "long" })} ${d.getFullYear()}`;
}
