// lib/__tests__/mom-document.test.mjs — the generated DOCX and PDF-HTML.
//
// Run:  node --test lib/__tests__/mom-document.test.mjs
//
// WHAT THIS PINS. These two renderers produce the artefact the user actually
// sends to other people, and a fault in either is invisible until someone
// opens the file. So the tests are about the failures that do not announce
// themselves:
//
//   CONTENT LOSS — every visible row, field, attendee and list item must
//     reach the output. A table that silently drops its 40th row still opens
//     fine in Word.
//
//   THE USER'S TEXT, NOT THE AI'S — the export must carry what the user
//     edited. This is the end of the chain the backend's merge protects, and
//     the only place it can still be lost.
//
//   INJECTION AND BREAKAGE — a pipe, an angle bracket or an ampersand in a
//     cell must not corrupt the table or inject markup. Cell text is user
//     input and can be anything.
//
//   TABLES THAT SPAN PAGES — the header row must repeat (OOXML tblHeader /
//     CSS thead), or page 2 of a long Action Items table is unlabelled cells.
//     "No clipping" on a phone-authored document mostly means "the renderer
//     was allowed to break the table", which is why the CSS must NOT set
//     page-break-inside: avoid on a whole grid.
//
// A .docx is a ZIP, so the DOCX assertions unzip it and read word/document.xml
// — checking the bytes are a real package, not just that a function returned
// something. fflate is a project dependency, so no new tooling is needed.
//
// The renderers are TypeScript, so their logic is mirrored below, matching the
// convention in task-insights.test.mjs and mom-model.test.mjs.
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { unzipSync, strFromU8 } from "fflate";

// --- mirrored from lib/mom-template.ts -------------------------------------

const T = {
  accent: "3E6BFF", accentSoft: "EEF2FF", ink: "12131A", inkDim: "5B6072",
  inkFaint: "9297A8", rule: "E6E9F0", zebra: "F7F8FB",
  titlePt: 22, subtitlePt: 13, headingPt: 12, bodyPt: 10.5, tablePt: 9.5,
  kickerPt: 8, footerPt: 8,
  pageWidthIn: 8.5, pageHeightIn: 11, marginIn: 0.9,
  company: "Exceller Tech",
  footerNote:
    "Generated by MinuteX from the meeting recording. Review before circulating.",
};

const CONTENT_WIDTH_IN = T.pageWidthIn - T.marginIn * 2;
const halfPt = (pt) => Math.round(pt * 2);
const twips = (inches) => Math.round(inches * 1440);
const CONTENT_WIDTH_TWIPS = twips(CONTENT_WIDTH_IN);

function columnWeights(labels) {
  if (!labels.length) return [];
  const weight = (label) => {
    const l = label.trim().toLowerCase();
    if (/^(sr\.?\s*no\.?|s\.?\s*no\.?|#|no\.?|index)$/.test(l)) return 0.55;
    if (/^(owner|name|by|assignee|responsible|status|priority)$/.test(l)) return 1.3;
    if (/^(date|time|deadline|due|when|target)$/.test(l)) return 1.1;
    if (/(point|discussion|description|detail|note|action|item|topic|remark)/.test(l)) return 2.6;
    return 1.6;
  };
  const raw = labels.map(weight);
  const total = raw.reduce((a, b) => a + b, 0);
  return raw.map((w) => w / total);
}

function escapeMarkup(s) {
  return String(s ?? "")
    .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

function templateDate(d = new Date()) {
  return `${d.getDate()} ${d.toLocaleString("en-GB", { month: "long" })} ${d.getFullYear()}`;
}

// --- mirrored from lib/mom-model.ts ----------------------------------------

function isSectionEmpty(section) {
  switch (section.kind) {
    case "fields":
      return !(section.fields ?? []).some((f) => f.visible && (f.label || f.value));
    case "table":
      return !(section.columns ?? []).length
        || !(section.rows ?? []).some((r) => r.visible);
    case "text":
      return !(section.text ?? "").trim();
    default:
      return !(section.items ?? []).some((i) => i.visible && i.text.trim());
  }
}

// --- mirrored from lib/mom-html.ts -----------------------------------------

function paragraphs(text) {
  return (text || "").split(/\n{2,}/).map((b) => b.trim()).filter(Boolean)
    .map((b) => `<p>${escapeMarkup(b).replace(/\n/g, "<br/>")}</p>`).join("");
}

function fieldsHtml(section) {
  const rows = (section.fields ?? [])
    .filter((f) => f.visible && (f.label || f.value))
    .map((f) => `<tr><th scope="row">${escapeMarkup(f.label)}</th>`
      + `<td>${escapeMarkup(f.value).replace(/\n/g, "<br/>")}</td></tr>`)
    .join("");
  return rows ? `<table class="kv">${rows}</table>` : "";
}

function tableHtml(section) {
  const columns = section.columns ?? [];
  const rows = (section.rows ?? []).filter((r) => r.visible);
  if (!columns.length || !rows.length) return "";
  const cols = columnWeights(columns.map((c) => c.label))
    .map((w) => `<col style="width:${(w * 100).toFixed(2)}%"/>`).join("");
  const head = columns.map((c) => `<th>${escapeMarkup(c.label)}</th>`).join("");
  const body = rows.map((r) => "<tr>" + columns
    .map((c) => `<td>${escapeMarkup(r.cells[c.id] ?? "").replace(/\n/g, "<br/>")}</td>`)
    .join("") + "</tr>").join("");
  return `<table class="grid"><colgroup>${cols}</colgroup>`
    + `<thead><tr>${head}</tr></thead><tbody>${body}</tbody></table>`;
}

function listHtml(section) {
  const items = (section.items ?? [])
    .filter((i) => i.visible && i.text.trim())
    .map((i) => `<li>${escapeMarkup(i.text).replace(/\n/g, "<br/>")}</li>`).join("");
  return items ? `<ul>${items}</ul>` : "";
}

function sectionHtml(section) {
  let body = "";
  if (section.kind === "fields") body = fieldsHtml(section);
  else if (section.kind === "table") body = tableHtml(section);
  else if (section.kind === "text") body = paragraphs(section.text ?? "");
  else body = listHtml(section);
  if (!body) return "";
  return `<section class="sec"><h2>${escapeMarkup(section.title)}</h2>${body}</section>`;
}

function momHtml(mom, meetingTitle) {
  const sections = mom.sections
    .filter((s) => s.visible && !isSectionEmpty(s))
    .map(sectionHtml).filter(Boolean).join("");
  const title = mom.title?.trim() || "Minutes of Meeting";
  const subtitle = mom.subtitle?.trim() || meetingTitle || "";
  const empty = '<section class="sec"><p class="empty">This MoM has no visible '
    + 'content yet. Add a section in the editor to see it here.</p></section>';
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/>
<title>${escapeMarkup(title)}</title>
<style>
  @page { size: ${T.pageWidthIn}in ${T.pageHeightIn}in; margin: ${T.marginIn}in; }
  body { font-size: ${T.bodyPt}pt; color: #${T.ink}; }
  h2 { font-size: ${T.headingPt}pt; color: #${T.accent};
       page-break-after: avoid; break-after: avoid; }
  .grid thead th { background: #${T.accent}; color: #fff; }
  .grid td { border: 1px solid #${T.rule}; word-break: break-word; }
  .grid tbody tr:nth-child(even) { background: #${T.zebra}; }
  .grid tr { page-break-inside: avoid; break-inside: avoid; }
  thead { display: table-header-group; }
</style></head><body>
<div class="masthead">
  <p class="kicker">${escapeMarkup(T.company)}</p>
  <h1>${escapeMarkup(title)}</h1>
  ${subtitle ? `<p class="subtitle">${escapeMarkup(subtitle)}</p>` : ""}
</div>
<div class="meta"><span>${escapeMarkup(templateDate())}</span></div>
${sections || empty}
<div class="footer"><span>${escapeMarkup(T.footerNote)}</span></div>
</body></html>`;
}

// --- mirrored from lib/mom-docx.ts -----------------------------------------

function run(text, o = {}) {
  const props = [
    o.bold ? "<w:b/>" : "", o.caps ? "<w:caps/>" : "",
    o.color ? `<w:color w:val="${o.color}"/>` : "",
    o.size ? `<w:sz w:val="${halfPt(o.size)}"/>` : "",
    o.spacing ? `<w:spacing w:val="${o.spacing}"/>` : "",
  ].join("");
  return `<w:r>${props ? `<w:rPr>${props}</w:rPr>` : ""}`
    + `<w:t xml:space="preserve">${escapeMarkup(text)}</w:t></w:r>`;
}

function para(runs, o = {}) {
  const props = [
    o.keepNext ? "<w:keepNext/>" : "",
    o.indent ? `<w:ind w:left="${o.indent}"/>` : "",
    (o.after != null || o.before != null)
      ? `<w:spacing${o.before != null ? ` w:before="${o.before}"` : ""}`
        + `${o.after != null ? ` w:after="${o.after}"` : ""}/>` : "",
    o.border
      ? `<w:pBdr><w:bottom w:val="single" w:sz="${o.borderSize ?? 8}" w:color="${o.border}"/></w:pBdr>`
      : "",
  ].join("");
  return `<w:p>${props ? `<w:pPr>${props}</w:pPr>` : ""}${runs}</w:p>`;
}

function multiline(text, o = {}) {
  const lines = String(text ?? "").split("\n");
  return lines.map((line, i) => para(run(line, o), {
    ...o, after: i === lines.length - 1 ? (o.after ?? 0) : 0,
  })).join("");
}

function cell(content, widthTwips, shade) {
  return `<w:tc><w:tcPr><w:tcW w:w="${widthTwips}" w:type="dxa"/>`
    + (shade ? `<w:shd w:val="clear" w:fill="${shade}"/>` : "")
    + `<w:tcMar><w:top w:w="60" w:type="dxa"/><w:bottom w:w="60" w:type="dxa"/>`
    + `<w:left w:w="90" w:type="dxa"/><w:right w:w="90" w:type="dxa"/></w:tcMar>`
    + `</w:tcPr>${content}</w:tc>`;
}

function gridTable(section) {
  const columns = section.columns ?? [];
  const rows = (section.rows ?? []).filter((r) => r.visible);
  if (!columns.length || !rows.length) return "";
  const widths = columnWeights(columns.map((c) => c.label))
    .map((w) => Math.max(400, Math.round(w * CONTENT_WIDTH_TWIPS)));
  const border = (side) => `<w:${side} w:val="single" w:sz="4" w:color="${T.rule}"/>`;
  const header = `<w:tr><w:trPr><w:tblHeader/></w:trPr>`
    + columns.map((c, i) => cell(
      para(run(c.label, { bold: true, color: "FFFFFF", size: T.kickerPt, caps: true, spacing: 8 }),
        { after: 0 }), widths[i], T.accent)).join("") + `</w:tr>`;
  const body = rows.map((r, ri) => `<w:tr>`
    + columns.map((c, ci) => cell(multiline(r.cells[c.id] ?? "", { size: T.tablePt }),
      widths[ci], ri % 2 === 1 ? T.zebra : undefined)).join("") + `</w:tr>`).join("");
  return `<w:tbl><w:tblPr><w:tblW w:w="${CONTENT_WIDTH_TWIPS}" w:type="dxa"/>`
    + `<w:tblLayout w:type="fixed"/><w:tblBorders>`
    + ["top", "left", "bottom", "right", "insideH", "insideV"].map(border).join("")
    + `</w:tblBorders></w:tblPr>`
    + `<w:tblGrid>${widths.map((w) => `<w:gridCol w:w="${w}"/>`).join("")}</w:tblGrid>`
    + header + body + `</w:tbl>`;
}

function fieldsTable(section) {
  const fields = (section.fields ?? []).filter((f) => f.visible && (f.label || f.value));
  if (!fields.length) return "";
  const labelWidth = Math.round(CONTENT_WIDTH_TWIPS * 0.33);
  const valueWidth = CONTENT_WIDTH_TWIPS - labelWidth;
  const rows = fields.map((f) => `<w:tr>`
    + cell(para(run(f.label, { bold: true, color: T.inkDim, size: T.bodyPt }), { after: 40 }), labelWidth)
    + cell(multiline(f.value, { size: T.bodyPt, after: 40 }), valueWidth) + `</w:tr>`).join("");
  return `<w:tbl><w:tblPr><w:tblW w:w="${CONTENT_WIDTH_TWIPS}" w:type="dxa"/>`
    + `<w:tblLayout w:type="fixed"/>`
    + `<w:tblBorders><w:top w:val="none"/><w:left w:val="none"/>`
    + `<w:bottom w:val="none"/><w:right w:val="none"/>`
    + `<w:insideH w:val="none"/><w:insideV w:val="none"/></w:tblBorders></w:tblPr>`
    + `<w:tblGrid><w:gridCol w:w="${labelWidth}"/><w:gridCol w:w="${valueWidth}"/></w:tblGrid>`
    + rows + `</w:tbl>`;
}

function listParagraphs(section) {
  return (section.items ?? []).filter((i) => i.visible && i.text.trim())
    .map((i) => `<w:p><w:pPr><w:numPr><w:ilvl w:val="0"/><w:numId w:val="1"/>`
      + `</w:numPr><w:spacing w:after="40"/></w:pPr>`
      + run(i.text, { size: T.bodyPt }) + `</w:p>`).join("");
}

function sectionXml(section) {
  let body = "";
  if (section.kind === "fields") body = fieldsTable(section);
  else if (section.kind === "table") body = gridTable(section);
  else if (section.kind === "text") {
    body = (section.text ?? "").split(/\n{2,}/).map((b) => b.trim()).filter(Boolean)
      .map((b) => multiline(b, { size: T.bodyPt, after: 120 })).join("");
  } else body = listParagraphs(section);
  if (!body) return "";
  return para(run(section.title, {
    bold: true, color: T.accent, size: T.headingPt, caps: true, spacing: 12,
  }), { before: 220, after: 90, keepNext: true }) + body + para("", { after: 60 });
}

const CONTENT_TYPES_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
  + `<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">`
  + `<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>`
  + `<Override PartName="/word/footer1.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>`
  + `</Types>`;

const FOOTER_XML = `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
  + `<w:ftr xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">`
  + `<w:p>` + run(T.footerNote, { size: T.footerPt, color: T.inkFaint })
  + `<w:r><w:instrText xml:space="preserve">PAGE</w:instrText></w:r>`
  + `</w:p></w:ftr>`;

function documentXml(mom, meetingTitle) {
  const title = mom.title?.trim() || "Minutes of Meeting";
  const subtitle = mom.subtitle?.trim() || meetingTitle || "";
  const masthead =
    para(run(T.company, { color: T.accent, size: T.kickerPt, bold: true, caps: true, spacing: 26 }), { after: 40 })
    + para(run(title, { bold: true, size: T.titlePt }), { after: subtitle ? 20 : 60 })
    + (subtitle
      ? para(run(subtitle, { size: T.subtitlePt, color: T.inkDim, bold: true }),
        { after: 60, border: T.accent, borderSize: 18 })
      : para("", { after: 0, border: T.accent, borderSize: 18 }))
    + para(run(templateDate(), { size: T.kickerPt, color: T.inkFaint }), { before: 80, after: 220 });
  const sections = mom.sections.filter((s) => s.visible && !isSectionEmpty(s))
    .map(sectionXml).join("");
  const body = sections
    || para(run("This MoM has no visible content yet.", { size: T.bodyPt, color: T.inkFaint }));
  const sectPr = `<w:sectPr><w:footerReference w:type="default" r:id="rId3"/>`
    + `<w:pgSz w:w="${twips(T.pageWidthIn)}" w:h="${twips(T.pageHeightIn)}"/>`
    + `<w:pgMar w:top="${twips(T.marginIn)}" w:right="${twips(T.marginIn)}" `
    + `w:bottom="${twips(T.marginIn)}" w:left="${twips(T.marginIn)}" w:footer="${twips(0.45)}"/>`
    + `</w:sectPr>`;
  return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
    + `<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main" `
    + `xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">`
    + `<w:body>${masthead}${body}${sectPr}</w:body></w:document>`;
}

// zipSync is only needed to prove the package round-trips; the real module
// zips the same parts.
import { zipSync, strToU8 } from "fflate";

function buildMomDocx(mom, meetingTitle) {
  return zipSync({
    "[Content_Types].xml": strToU8(CONTENT_TYPES_XML),
    "word/document.xml": strToU8(documentXml(mom, meetingTitle)),
    "word/footer1.xml": strToU8(FOOTER_XML),
  }, { level: 6 });
}

/** Unzip a generated .docx and return word/document.xml as text. */
function docxBody(mom, meetingTitle = "Meeting") {
  const files = unzipSync(buildMomDocx(mom, meetingTitle));
  assert.ok(files["word/document.xml"], "package has no document part");
  return strFromU8(files["word/document.xml"]);
}

// --- fixtures ---------------------------------------------------------------

function mom(sections, over = {}) {
  return {
    title: "Minutes of Meeting", subtitle: "Internal Task Portal",
    sections, deleted_ids: [], mom_version: "1",
    generated_at: "", updated_at: "", transcript_fingerprint: "",
    speaker_mapping_version: 0, ...over,
  };
}

function table(id, title, columnLabels, rowValues) {
  const columns = columnLabels.map((label, i) => ({
    id: `c_${id}_${i}`, label, source: "ai",
  }));
  const rows = rowValues.map((values, ri) => ({
    id: `r_${id}_${ri}`, visible: true, source: "ai",
    cells: Object.fromEntries(columns.map((c, ci) => [c.id, values[ci] ?? ""])),
  }));
  return { id, kind: "table", title, visible: true, source: "ai", role: "",
           columns, rows };
}

const FULL = mom([
  {
    id: "s_d", kind: "fields", title: "Meeting Details", visible: true,
    source: "ai", role: "meeting_details",
    fields: [
      { id: "f1", label: "Date", value: "19 August 2026", visible: true, source: "ai" },
      { id: "f2", label: "Time", value: "3:30 PM - 4:00 PM", visible: true, source: "ai" },
    ],
  },
  table("s_a", "Action Items", ["Sr. No", "Action Item", "Owner"], [
    ["1", "Complete OAuth integration", "Rohan"],
    ["2", "Write the migration script", "Priya"],
  ]),
  {
    id: "s_h", kind: "list", title: "Highlights", visible: true, source: "ai", role: "highlights",
    items: [{ id: "i1", text: "OAuth is nearly done", visible: true, source: "ai" }],
  },
  {
    id: "s_s", kind: "text", title: "Summary", visible: true, source: "ai", role: "summary",
    text: "The team reviewed progress.",
  },
]);

// ===========================================================================
describe("DOCX — the package", () => {
  it("is a real zip with the parts Word needs", () => {
    const files = unzipSync(buildMomDocx(FULL));
    for (const part of ["[Content_Types].xml", "word/document.xml", "word/footer1.xml"]) {
      assert.ok(files[part], `missing ${part}`);
    }
  });

  it("declares the footer part, so the page number is not a dangling ref", () => {
    const files = unzipSync(buildMomDocx(FULL));
    assert.match(strFromU8(files["[Content_Types].xml"]), /footer1\.xml/);
    assert.match(docxBody(FULL), /<w:footerReference/);
  });

  it("uses a real PAGE field rather than a number we invented", () => {
    const files = unzipSync(buildMomDocx(FULL));
    assert.match(strFromU8(files["word/footer1.xml"]), /instrText[^>]*>PAGE</);
  });

  it("has one well-formed body with page size and margins", () => {
    const xml = docxBody(FULL);
    assert.equal((xml.match(/<w:body>/g) ?? []).length, 1);
    assert.match(xml, new RegExp(`<w:pgSz w:w="${twips(8.5)}" w:h="${twips(11)}"`));
    assert.match(xml, new RegExp(`w:top="${twips(0.9)}"`));
  });

  it("opens every tag it closes in the table markup", () => {
    const xml = docxBody(FULL);
    for (const tag of ["w:tbl", "w:tr", "w:tc", "w:p", "w:r"]) {
      const open = (xml.match(new RegExp(`<${tag}[ >]`, "g")) ?? []).length;
      const close = (xml.match(new RegExp(`</${tag}>`, "g")) ?? []).length;
      assert.equal(open, close, `${tag}: ${open} open vs ${close} close`);
    }
  });
});

describe("DOCX — content reaches the file", () => {
  it("carries the masthead, every section title and every value", () => {
    const xml = docxBody(FULL);
    assert.ok(xml.includes("Exceller Tech"));
    assert.ok(xml.includes("Minutes of Meeting"));
    assert.ok(xml.includes("Internal Task Portal"));
    for (const text of ["Meeting Details", "19 August 2026", "Action Items",
                        "Complete OAuth integration", "Rohan", "Highlights",
                        "OAuth is nearly done", "Summary",
                        "The team reviewed progress."]) {
      assert.ok(xml.includes(text), `missing: ${text}`);
    }
  });

  it("exports the USER's text, not the AI's original", () => {
    // The end of the chain the backend's merge protects.
    const edited = mom([
      { id: "s_s", kind: "text", title: "Summary", visible: true,
        source: "user_edited", role: "summary",
        text: "Complete OAuth integration and test Salesforce connection." },
    ]);
    const xml = docxBody(edited);
    assert.ok(xml.includes("test Salesforce connection"));
  });

  it("omits hidden sections, rows and fields", () => {
    const hidden = mom([
      { ...FULL.sections[0], fields: [
        { ...FULL.sections[0].fields[0], visible: false },
        FULL.sections[0].fields[1],
      ] },
      { ...FULL.sections[1], rows: [
        { ...FULL.sections[1].rows[0], visible: false },
        FULL.sections[1].rows[1],
      ] },
      { ...FULL.sections[3], visible: false },
    ]);
    const xml = docxBody(hidden);
    assert.equal(xml.includes("19 August 2026"), false);
    assert.ok(xml.includes("3:30 PM"));
    assert.equal(xml.includes("Complete OAuth integration"), false);
    assert.ok(xml.includes("Write the migration script"));
    assert.equal(xml.includes("The team reviewed progress."), false);
  });

  it("drops a section whose content is entirely empty, heading included", () => {
    const xml = docxBody(mom([
      { id: "s_e", kind: "list", title: "Decisions", visible: true,
        source: "ai", role: "decisions", items: [] },
      FULL.sections[3],
    ]));
    assert.equal(xml.includes("Decisions"), false);
    assert.ok(xml.includes("Summary"));
  });

  it("renders section order as the user arranged it", () => {
    const reordered = mom([FULL.sections[1], FULL.sections[0]]);
    const xml = docxBody(reordered);
    assert.ok(xml.indexOf("Action Items") < xml.indexOf("Meeting Details"));
  });

  it("an empty MoM still produces a valid document", () => {
    const xml = docxBody(mom([]));
    assert.match(xml, /<w:body>/);
    assert.ok(xml.includes("no visible content"));
  });
});

describe("DOCX — tables that span pages, and text that could clip", () => {
  it("marks the header row to repeat across a page break", () => {
    // Without tblHeader, page 2 of a long table is unlabelled cells.
    assert.match(docxBody(FULL), /<w:trPr><w:tblHeader\/><\/w:trPr>/);
  });

  it("keeps every row of a long table", () => {
    const big = table("big", "Action Items", ["Sr. No", "Action Item", "Owner"],
      Array.from({ length: 60 }, (_, i) => [String(i + 1), `Task number ${i}`, `Owner ${i}`]));
    const xml = docxBody(mom([big]));
    assert.ok(xml.includes("Task number 0"));
    assert.ok(xml.includes("Task number 59"));
    // header + 60 body rows
    assert.equal((xml.match(/<w:tr>/g) ?? []).length, 61);
  });

  it("keeps every attendee when there are many", () => {
    const many = table("att", "Attendees", ["Sr. No", "Name", "Role / Contribution"],
      Array.from({ length: 40 }, (_, i) => [String(i + 1), `Person ${i}`, "Contributed"]));
    const xml = docxBody(mom([many]));
    assert.ok(xml.includes("Person 0"));
    assert.ok(xml.includes("Person 39"));
  });

  it("column widths always sum to the text column, whatever the headers", () => {
    // A total wider than the page is what pushes the last column off the sheet.
    for (const labels of [
      ["Sr. No", "Discussion Point", "Action Item", "Owner", "Deadline"],
      ["A"], ["Sr. No", "Owner"],
      ["Sr. No", "Topic", "Discussion Point", "Action Item", "Owner", "Deadline"],
    ]) {
      const widths = columnWeights(labels)
        .map((w) => Math.max(400, Math.round(w * CONTENT_WIDTH_TWIPS)));
      const total = widths.reduce((a, b) => a + b, 0);
      assert.ok(total <= CONTENT_WIDTH_TWIPS + labels.length,
        `${labels.length} columns overflow: ${total} > ${CONTENT_WIDTH_TWIPS}`);
      for (const w of widths) assert.ok(w >= 400, "a column too narrow to read");
    }
  });

  it("gives a prose column more room than an index column", () => {
    const labels = ["Sr. No", "Discussion Point", "Owner"];
    const [no, point, owner] = columnWeights(labels);
    assert.ok(point > owner, "prose should be widest");
    assert.ok(owner > no, "an index column should be narrowest");
  });

  it("a very long cell is kept whole rather than truncated", () => {
    const long = "x".repeat(4000);
    const xml = docxBody(mom([table("l", "Notes", ["Detail"], [[long]])]));
    assert.ok(xml.includes(long), "cell text was truncated");
  });

  it("a newline in a cell becomes a paragraph break, not a broken run", () => {
    const xml = docxBody(mom([table("n", "Notes", ["Detail"], [["one\ntwo"]])]));
    assert.ok(xml.includes("one"));
    assert.ok(xml.includes("two"));
    assert.equal(xml.includes("one\ntwo"), false);
  });

  it("keeps a heading with the content beneath it", () => {
    // keepNext stops a heading being orphaned at the foot of a page.
    assert.match(docxBody(FULL), /<w:keepNext\/>/);
  });
});

describe("DOCX — text is escaped, never injected", () => {
  it("escapes XML metacharacters in cells, titles and values", () => {
    const nasty = mom([
      table("x", "Risks & <Issues>", ["Detail"], [['A & B <tag> "q" \'s\'']]),
    ]);
    const xml = docxBody(nasty);
    assert.ok(xml.includes("A &amp; B &lt;tag&gt;"));
    assert.equal(/<tag>/.test(xml), false, "raw tag reached the XML");
    assert.ok(xml.includes("Risks &amp; &lt;Issues&gt;"));
  });

  it("a closing tag typed into a cell cannot end the document", () => {
    const xml = docxBody(mom([
      table("y", "Notes", ["Detail"], [["</w:t></w:r></w:p></w:body>"]]),
    ]));
    assert.equal((xml.match(/<\/w:body>/g) ?? []).length, 1);
    assert.ok(xml.includes("&lt;/w:t&gt;"));
  });

  it("preserves leading and trailing spaces in a run", () => {
    const xml = docxBody(mom([table("z", "Notes", ["Detail"], [["  padded  "]])]));
    assert.match(xml, /<w:t xml:space="preserve">/);
  });
});

describe("PDF HTML", () => {
  it("carries the same content as the DOCX", () => {
    const html = momHtml(FULL, "Meeting");
    for (const text of ["Exceller Tech", "Minutes of Meeting", "Meeting Details",
                        "19 August 2026", "Action Items", "Complete OAuth integration",
                        "Rohan", "OAuth is nearly done", "The team reviewed progress."]) {
      assert.ok(html.includes(text), `missing: ${text}`);
    }
  });

  it("repeats the table header across pages", () => {
    const html = momHtml(FULL, "Meeting");
    assert.match(html, /<thead>/);
    assert.match(html, /thead \{ display: table-header-group; \}/);
  });

  it("lets a long table BREAK across pages", () => {
    // page-break-inside: avoid on a whole grid is what pushes a 60-row table
    // off the sheet. Rows avoid breaking; the table itself must not.
    const html = momHtml(FULL, "Meeting");
    assert.match(html, /\.grid tr \{ page-break-inside: avoid/);
    assert.equal(/table \{[^}]*page-break-inside:\s*avoid/.test(html), false);
  });

  it("sets a real page size and margins", () => {
    const html = momHtml(FULL, "Meeting");
    assert.match(html, /@page \{ size: 8\.5in 11in; margin: 0\.9in; \}/);
  });

  it("wraps a long unbroken string instead of letting it overflow", () => {
    assert.match(momHtml(FULL, "Meeting"), /word-break: break-word/);
  });

  it("escapes HTML in content", () => {
    const html = momHtml(mom([
      table("x", "Notes", ["Detail"], [["<script>alert(1)</script>"]]),
    ]), "Meeting");
    assert.equal(html.includes("<script>"), false);
    assert.ok(html.includes("&lt;script&gt;"));
  });

  it("renders every row of a long table", () => {
    const big = table("big", "Action Items", ["Sr. No", "Action Item", "Owner"],
      Array.from({ length: 60 }, (_, i) => [String(i + 1), `Task ${i}`, `Owner ${i}`]));
    const html = momHtml(mom([big]), "Meeting");
    assert.ok(html.includes("Task 0"));
    assert.ok(html.includes("Task 59"));
    assert.equal((html.match(/<tr>/g) ?? []).length, 61);
  });

  it("column widths sum to 100%", () => {
    const html = momHtml(FULL, "Meeting");
    const widths = [...html.matchAll(/width:([\d.]+)%/g)].map((m) => Number(m[1]));
    assert.ok(widths.length >= 3);
    const total = widths.slice(0, 3).reduce((a, b) => a + b, 0);
    assert.ok(Math.abs(total - 100) < 0.1, `columns sum to ${total}%`);
  });

  it("an empty MoM still produces a valid page", () => {
    const html = momHtml(mom([]), "Meeting");
    assert.match(html, /<!DOCTYPE html>/);
    assert.ok(html.includes("no visible content"));
  });
});

describe("the two renderers agree", () => {
  it("both use the template accent, not their own colour", () => {
    assert.ok(momHtml(FULL, "Meeting").includes(`#${T.accent}`));
    assert.ok(docxBody(FULL).includes(T.accent));
  });

  it("both include the footer note", () => {
    assert.ok(momHtml(FULL, "Meeting").includes(T.footerNote));
    const files = unzipSync(buildMomDocx(FULL));
    assert.ok(strFromU8(files["word/footer1.xml"]).includes(T.footerNote));
  });

  it("both drop exactly the same sections", () => {
    const mixed = mom([
      FULL.sections[0],
      { id: "s_e", kind: "list", title: "Empty", visible: true, source: "ai",
        role: "", items: [] },
      { ...FULL.sections[3], visible: false },
    ]);
    const html = momHtml(mixed, "Meeting");
    const xml = docxBody(mixed);
    for (const doc of [html, xml]) {
      assert.ok(doc.includes("Meeting Details"));
      assert.equal(doc.includes("Empty"), false);
      assert.equal(doc.includes("The team reviewed progress."), false);
    }
  });
});
